### ISSUE TITLE
L1 : Fix recurssion for sum of array.

### ISSUE THREAD

**Issue by Kevin-Aaaquil** [srm-kzilla/slither-into-open-source#11]
# Expected Behavior

* Take an array of size n as input
* return output

# Current Behavior

* Does not return any output

## Steps to Reproduce

* Enter the size of the array
* Enter integers in the array

**Comment by Georgezogos** [comment]
Hello, could I work on that?

**Comment by Georgezogos** [comment]
Hello @Kevin-Aaaquil , could you please accept the pull request in order for me to complete the hacktoberfest challenge?
