### ISSUE TITLE
L1 : Fix Bubble Sort

### ISSUE THREAD

**Issue by Kevin-Aaaquil** [srm-kzilla/slither-into-open-source#14]
https://github.com/srm-kzilla/slither-into-open-source/blob/main/Level-I/bubbleSort.c

# Expected Behavior

* Take input from the user for unsorted array

# Current Behavior

* Array is hardcoded 
* Code returns numerous errors

**Comment by kashish0604** [comment]
hey @Kevin-Aaaquil can you assign this issue to me i can work on it

**Comment by idrismusa4** [comment]
@Kevin-Aaaquil can the code be rewritten?

**Comment by shawshankkumar** [comment]
Yeah sure make a pr.

**Comment by kashish0604** [comment]
@shawshankkumar please accept my PR
