### ISSUE TITLE
L1 : Fix Merge Sort bugs

### ISSUE THREAD

**Issue by Kevin-Aaaquil** [srm-kzilla/slither-into-open-source#15]
https://github.com/srm-kzilla/slither-into-open-source/blob/main/Level-I/mergeSort.js

# Expected Behavior

* Take array as input from user
* Return sorted array

# Current Behavior

* Array is hardcoded
* Code throws numerous errors

**Comment by kashish0604** [comment]
hey @Kevin-Aaaquil can u assign this issue to me i can work on it

**Comment by kashish0604** [comment]
done please my PR

**Comment by kashish0604** [comment]
@Kevin-Aaaquil please accept my PR
